### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LeonBoettcher** [seanlego23/RegionResourcePacks#1]
My consoled get this error message spammed if a player moves

[14:09:42 WARN]: [RegionResourcePacks] __global__ region could not be found.

**Comment by seanlego23** [comment]
Thank you for making me aware of this bug. Modify the __global__ region in each of your worlds (including nether and the end) and that should nullify the problem. You can modify each __global__ region to have the empty resource pack (unless you have a server resource pack) included in the release as well.

**Comment by seanlego23** [comment]
v1.1.1 fixes this bug and another subsequent bug if your server resource pack was null or invalid.
